BEGIN;

CREATE TABLE IF NOT EXISTS "dbo"."biz_steel_beam_theoretical" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjID" integer NOT NULL,
    "BridgeID" integer NOT NULL,
    "PointCode" varchar(50) NOT NULL,
    "DesignX" decimal(20,6) NOT NULL,
    "DesignY" decimal(20,6) NOT NULL,
    "DesignZ" decimal(20,6) NOT NULL,
    "PreCamber" decimal(20,6) NOT NULL,
    "Weight" decimal(5,4) NOT NULL,
    "SegmentNo" varchar(50) NOT NULL,
    "PositionName" varchar(100) NOT NULL,
    "IsFirstCoordinate" boolean NULL,
    "PositionOrder" integer NULL,
    "DistanceFromStart" decimal(20,6) NULL,
    "Version" integer NOT NULL DEFAULT 1,
    "Status" integer NOT NULL DEFAULT 0,
    "CreatedBy" varchar(100) NULL,
    "CreatedTime" timestamp NULL,
    "UpdatedBy" varchar(100) NULL,
    "UpdatedTime" timestamp NULL
);

CREATE TABLE IF NOT EXISTS "dbo"."biz_steel_beam_measure_batch" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjID" integer NOT NULL,
    "BridgeID" integer NOT NULL,
    "PushCount" integer NOT NULL,
    "MeasureTime" timestamp NOT NULL,
    "ImportCount" integer NOT NULL,
    "ReplacedByBatchID" integer NULL,
    "Status" integer NOT NULL DEFAULT 0,
    "CreatedBy" varchar(100) NULL,
    "CreatedTime" timestamp NULL,
    "UpdatedBy" varchar(100) NULL,
    "UpdatedTime" timestamp NULL
);

CREATE TABLE IF NOT EXISTS "dbo"."biz_steel_beam_measured" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ProjID" integer NOT NULL,
    "BridgeID" integer NOT NULL,
    "BatchID" integer NOT NULL,
    "TheoreticalID" integer NOT NULL,
    "PointCode" varchar(50) NOT NULL,
    "MeasuredX" decimal(20,6) NOT NULL,
    "MeasuredY" decimal(20,6) NOT NULL,
    "MeasuredZ" decimal(20,6) NOT NULL,
    "ImportTime" timestamp NOT NULL,
    "Version" integer NOT NULL DEFAULT 1,
    "Status" integer NOT NULL DEFAULT 0,
    "CreatedBy" varchar(100) NULL,
    "CreatedTime" timestamp NULL,
    "UpdatedBy" varchar(100) NULL,
    "UpdatedTime" timestamp NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_SteelTheory_Project_PointCode"
    ON "dbo"."biz_steel_beam_theoretical" ("ProjID", lower("PointCode")) WHERE "Status" <> -1;
CREATE INDEX IF NOT EXISTS "IX_SteelTheory_Bridge_Status"
    ON "dbo"."biz_steel_beam_theoretical" ("BridgeID", "Status");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_SteelBatch_Bridge_Push_Time"
    ON "dbo"."biz_steel_beam_measure_batch" ("BridgeID", "PushCount", "MeasureTime") WHERE "Status" <> -1;
CREATE INDEX IF NOT EXISTS "IX_SteelBatch_Bridge_Status"
    ON "dbo"."biz_steel_beam_measure_batch" ("BridgeID", "Status", "PushCount", "MeasureTime");
CREATE UNIQUE INDEX IF NOT EXISTS "UX_SteelMeasured_Batch_Point"
    ON "dbo"."biz_steel_beam_measured" ("BatchID", lower("PointCode")) WHERE "Status" <> -1;
CREATE INDEX IF NOT EXISTS "IX_SteelMeasured_Bridge_Point"
    ON "dbo"."biz_steel_beam_measured" ("BridgeID", "Status", "PointCode");

COMMIT;
